//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: append_entries_request.proto
// Note: requires additional types generated from: log_entry.proto
namespace protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppendEntriesRequest")]
  public partial class AppendEntriesRequest : global::ProtoBuf.IExtensible
  {
    public AppendEntriesRequest() {}
    
    private uint _Term;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Term", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Term
    {
      get { return _Term; }
      set { _Term = value; }
    }
    private uint _PrevLogIndex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PrevLogIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PrevLogIndex
    {
      get { return _PrevLogIndex; }
      set { _PrevLogIndex = value; }
    }
    private uint _PrevLogTerm;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"PrevLogTerm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PrevLogTerm
    {
      get { return _PrevLogTerm; }
      set { _PrevLogTerm = value; }
    }
    private uint _CommitIndex;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"CommitIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CommitIndex
    {
      get { return _CommitIndex; }
      set { _CommitIndex = value; }
    }
    private string _LeaderName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"LeaderName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string LeaderName
    {
      get { return _LeaderName; }
      set { _LeaderName = value; }
    }
    private global::System.Collections.Generic.List<protobuf.LogEntry> _Entries = new global::System.Collections.Generic.List<protobuf.LogEntry>();
    [global::ProtoBuf.ProtoMember(6, Name = @"Entries", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protobuf.LogEntry> Entries
    {
      get { return _Entries; }
      set { _Entries = value; }
     }

        private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}