//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/log_entry.proto
namespace protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogEntry")]
  public partial class LogEntry : global::ProtoBuf.IExtensible
  {
    public LogEntry() {}
    
    private uint _Index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Index
    {
      get { return _Index; }
      set { _Index = value; }
    }
    private uint _Term;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Term", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Term
    {
      get { return _Term; }
      set { _Term = value; }
    }
    private string _CommandName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"CommandName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CommandName
    {
      get { return _CommandName; }
      set { _CommandName = value; }
    }

    private byte[] _Command = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Command", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] Command
    {
      get { return _Command; }
      set { _Command = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}