//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/request_vote_responses.proto
namespace protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestVoteResponse")]
  public partial class RequestVoteResponse : global::ProtoBuf.IExtensible
  {
    public RequestVoteResponse() {}
    
    private uint _Term;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Term", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Term
    {
      get { return _Term; }
      set { _Term = value; }
    }
    private bool _VoteGranted;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"VoteGranted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool VoteGranted
    {
      get { return _VoteGranted; }
      set { _VoteGranted = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}