//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/snapshot_request.proto
namespace protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SnapshotRequest")]
  public partial class SnapshotRequest : global::ProtoBuf.IExtensible
  {
    public SnapshotRequest() {}
    
    private string _LeaderName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"LeaderName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string LeaderName
    {
      get { return _LeaderName; }
      set { _LeaderName = value; }
    }
    private uint _LastIndex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"LastIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LastIndex
    {
      get { return _LastIndex; }
      set { _LastIndex = value; }
    }
    private uint _LastTerm;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"LastTerm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LastTerm
    {
      get { return _LastTerm; }
      set { _LastTerm = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}